EXPORT_PATH = "data/cleaned_data.csv"
GEMINI_API_KEY = "your-gemini-key-here"
GCP_PROJECT_ID = "trendnest-463421"
BQ_DATASET = "trendnest"
BQ_TABLE = "cleaned_stock_data"
GOOGLE_APPLICATION_CREDENTIALS = "gcp_key.json"