EXPORT_PATH = "data/cleaned_data.csv"
GEMINI_API_KEY = "AIzaSyB85mtJO4yhMk9GBMDHR9_fWT_ospWYSaM"
GCP_PROJECT_ID = "trendnest-463421"
BQ_DATASET = "trendnest"
BQ_TABLE = "cleaned_stock_data"
GOOGLE_APPLICATION_CREDENTIALS = ".gcp/trendnest-463421-0ec9eec13395.json"